flowchart LR
Vendor --->|FAVIP|IQC_NofurthurSamplingPan ---> 茂林 --->|FAVIP|IQC_NofurthurSamplingPan --->|AppearanceStandard|T1 ---> |AppearanceStandard|T2_NoProcessWalk ---> |TrayVnV|T1 ---> |ProcessWalk|Ship